name: Build EXE for Windows

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: "windows-latest"

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Install Node.js and NPM
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Compile Electron App
              uses: x6Pnda/action-electron-compiler@v1.0.1
              with:
                  # GitHub token, automatically provided to the action
                  # (Optional)
                  github_token: ${{ secrets.github_token }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # (Optional)
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}

                  # Package manager. NPM, PNPM and Yarn supported. Install Yarn and PNPM yourself. Default is NPM
                  # (Optional)
                  package_manager: NPM

                  # Skip buiding the application
                  # (Optional)
                  skip_build: false